version: '3.7'
services:
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/home/node/client:cached
    env_file:
      - devenv/.env
    ports:
      - "5000:5000"
      - "35729:35729"
    command: npm run build
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/home/node/app:cached
    command: npm run dev
    env_file:
      - devenv/.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:11.0-alpine
    restart: always
    env_file:
      - devenv/.env
    ports:
      - '5432:5432'
