version: '3.7'
services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/home/node/app:cached
    command: npm run dev
    env_file:
      - devenv/.env
    environment:
      - DB_HOST=host.docker.internal
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres:11.0-alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - '5432:5432'
