export * from './event.repository';
export * from './location.repository';
export * from './organization.repository';
export * from './person.repository';
export * from './room.repository';
export * from './talk.repository';
export * from './topic.repository';
export * from './talk_date.repository';
export * from './talk_topic.repository';
