image:
  repository: mnikolic/pac_mnikolic_api
  tag: latest
envFrom:
- configMapRef:
    name: backend-config
- secretRef:
    name: backend-postgres-access
ingress:
  enabled: true
  hosts:
    - host: conference.backend
      paths:
        - "/"
