name: 'api'

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [master]
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        working-directory: api
        run: docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push ${GITHUB_REPOSITORY}:latest