name: 'api'

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [master]
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Bootstrap project
        working-directory: api
        run: |
          npm install

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        working-directory: api
        run: npm run docker:build

      - name: Tag image
        run: docker tag pac_mnikolic_api:latest api:latest

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push mnikolic/pac_mnikolic_api:latest