name: 'api'

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [master]
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t mnikolic/pac_mnikolic_api .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push mnikolic/pac_mnikolic_api