name: 'client'

# Controls when the action will run.
on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI: true
      SVELTE_APP_BE_URL: "http://conference.backend/graphql"
      SVELTE_APP_CLIENT_ID: "0oaup7oeuqIcBZjyw4x6"
      SVELTE_APP_ISSUER: "https://dev-269607.okta.com"
      SVELTE_APP_OKTA_TESTING_DISABLEHTTPSCHECK: "false"
      SVELTE_APP_REDIRECT_OKTA_URL: "http://conference.frontend/"
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Install necessary dependency
      - name: 'Install dependencies'
        working-directory: client
        run: |
          npm install

      # Build the project
      - name: 'Build project'
        working-directory: client
        run: |
          npm run build
